language: java
dist: trusty
branches:
  only:
    - master
jdk:
  - openjdk8
env:
  - HADOOP_PROFILE=default TEST_CODECS=gzip,snappy
sudo: required
before_install:
  - bash dev/travis-before_install.sh
install:
  mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)
jobs:
  include:
    - stage: test
      name: "Check"
      script: mvn verify --batch-mode javadoc:javadoc -P $HADOOP_PROFILE
    - stage: publish
      if: branch = master AND type = push OR commit_message = PUBLISH
      name: "Publish"
      script: mvn deploy
